name: Test IPython beamline profiles

on:
  push:
    branches:
      - main
      - add-gha-ci
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testing_beamline_profiles:
    name: ${{ matrix.repos.beamline-acronym }}
    strategy:
      fail-fast: false
      matrix:
        repos:
          - org: "NSLS2"
            repo: "ios-profile-collection"
            branch: ""
            beamline-acronym: "ios"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Integration Tests Against Beamline Profiles
        uses: NSLS2/gha-beamline-integration-test@ios-redis-ssl-config
        with:
          org: "${{ matrix.repos.org }}"
          repo: "${{ matrix.repos.repo }}"
          branch: "${{ matrix.repos.branch }}"
          beamline-acronym: "${{ matrix.repos.beamline-acronym }}"
          test-queueserver: 'true'
